### ISSUE TITLE
NSFW not loading.

### ISSUE THREAD

**Issue by jeroneemou** [mRtyu/scrolller#1]
Hey man, the best section of you website stopped working! Would you have a time to look at it? 
Checkout screenshot.
![NSFW (Reddit Gallery) - Scrolller - Google Chrome 7_26_2020 4_07_19 PM](https://user-images.githubusercontent.com/2467722/88481356-4ed86700-cf5b-11ea-9514-3ab107ed6ba1.png)

Thank you!

**Comment by mRtyu** [comment]
Closing this as it is fixed and working.

Thanks for your feedback @jeroneemou.
